### ISSUE TITLE
I'm having a problem of using it.

### ISSUE THREAD

**Issue by bladeism** [w-shackleton/android-netspoof#10]
I tried all the features but nothing works. I saw Segmentation fault and Code line not exist I think it is the data from your server. 

I'm using huawei ascend y210-0100.

Thank you!

**Comment by w-shackleton** [comment]
I have just released [Network Spoofer 2.1.0](https://github.com/w-shackleton/android-netspoof/releases/tag/2.1.0) - please can you check whether this issue still happens with this new version (the app will prompt to update).

**Comment by w-shackleton** [comment]
Closing since no details given.
