### ISSUE TITLE
tiestot9

### ISSUE THREAD

**Issue by tiestot9** [w-shackleton/android-netspoof#107]
Merci

**Comment by tiestot9** [comment]
Hi

**Comment by w-shackleton** [comment]
What do you want? I'm very confused as to why this issue exists.

**Comment by iKlem** [comment]
The first message says "Thanks" in french but i don't know why he's doing this. I think you can close this.

**Comment by w-shackleton** [comment]
I was more confused by the title being the username, the closing and re-opening. Ah well.

This project gets so many strange and obscure issues being filed against it
