### ISSUE TITLE
Permanent?

### ISSUE THREAD

**Issue by Systemad** [w-shackleton/android-netspoof#110]
I download Network Spoofer and it worked fine, while I was brwosing the MITM attacks I saw "redirect" attack.
I chose my computer to redirect to a webiste (obviously) and it worked, I turned off Network Spoofer and  exited the app. My problem is, my computer still redirects to that website (only when I enter the website when I tested) still, I restarted my computer and still same thing.

**Comment by w-shackleton** [comment]
Clearing your browser cache will fix this.

**Comment by Systemad** [comment]
Yeah, I thought so too but it didn't 
I cleared both cache and whole chrome data. Still redirects me.
