### ISSUE TITLE
Spoofs not working

### ISSUE THREAD

**Issue by marcianosr** [w-shackleton/android-netspoof#112]
Hello, 

I'm trying to run networkspoofer (2.4) over bluestacks, and if I pick a random spoof and I let it scan for devices, I add an ip address which is locally in my wifi network (192.x.x.x), but it says: 
 `ip tables failed
couldnt find a cached mac addres for 192.x.x.x`. 

Any idea's? 

Thanks.

**Comment by w-shackleton** [comment]
I haven't used bluestacks but it will most likely be putting devices behind a NAT firewall rather than assigning them IP addresses inside the target network - this means that Network Spoofer can't work from Bluestacks I'm afraid.
