### ISSUE TITLE
Doesn't work on HTTPS?

### ISSUE THREAD

**Issue by diegotrigo** [w-shackleton/android-netspoof#116]
Hi there,
Not sure if it's a bug or a feature request (or even possible at all), but it doesn't seem to work over HTTPs. 

If I want to, say replace an image, if HTTPS I understand the content of the image would be encrypted, but the spoofer would still capture that "an image" (encrypted) is going through the router, right? Meaning we'd still be able to replace it, I believe.

Is this right?

Thanks,
D

**Comment by w-shackleton** [comment]
TLS (and hence HTTPS) provide confidentiality as well as integrity - I'd recommend [reading up on these](http://security.blogoverflow.com/2012/08/confidentiality-integrity-availability-the-three-components-of-the-cia-triad/) to figure out why this can't work. There are programs like SSLStrip that attempt to coax users out of HTTPS but schemes like HSTS are designed to block such attacks.

**Comment by diegotrigo** [comment]
Awesome.. thanks for getting back to me...
Cheers,
D
