### ISSUE TITLE
Isn't working for Nexus 7

### ISSUE THREAD

**Issue by Psych0tic** [w-shackleton/android-netspoof#125]
Hello,
So I pressed on the YouTube video change to Rick roll thing. And I chose to hack people all around my WiFi, and then I pressed start, and it loaded so I tried it on my laptop, went on YouTube clicked a video, but nothing happened... I also tried it with every single hack. Please reply and help!

**Comment by w-shackleton** [comment]
YouTube uses HTTPS, which won't work with Network Spoofer - Network Spoofer can only change websites that use HTTP.
