### ISSUE TITLE
not working on S5 

### ISSUE THREAD

**Issue by jollyrodger** [w-shackleton/android-netspoof#14]
I'm having the following issue.  I have su privilege through SuperSu.  It routes the ip tables and then redirectsto port 3128  and shows the app location and permission denied

**Comment by w-shackleton** [comment]
I have just released [Network Spoofer 2.1.0](https://github.com/w-shackleton/android-netspoof/releases/tag/2.1.0) - please can you check whether this issue still happens with this new version (the app will prompt to update).

**Comment by w-shackleton** [comment]
Closing since no details given.
