### ISSUE TITLE
PLEASE FIX AS SOON AS POSSIBLE

### ISSUE THREAD

**Issue by ZoeiraNeverEnds** [w-shackleton/android-netspoof#157]
My cellphone is a Samsung Galaxy S3, I have root, and I have so many bugs on the app (Nework Spoofer), NOTHING WORKS!, I tested the app on 5 cellphones, and none of them worked (I have busybox pro, and root in all of them)

**Comment by w-shackleton** [comment]
PULL REQUESTS WELCOME.
