### ISSUE TITLE
hii

### ISSUE THREAD

**Issue by luisweller16** [w-shackleton/android-netspoof#16]
pues que no me deja descargar los archivos exttas porq no tengo tarjeta sd porq mi movil solo tiene memoria interna deveria poderse aser sin tarjeta gracias

**Comment by w-shackleton** [comment]
I have just released [Network Spoofer 2.1.0](https://github.com/w-shackleton/android-netspoof/releases/tag/2.1.0) - please can you check whether this issue still happens with this new version (the app will prompt to update).

**Comment by w-shackleton** [comment]
Closing since no details given.
