### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by angelo16s** [w-shackleton/android-netspoof#17]
La app no funciona en mi Lg L3..CianogenMod kitkat v2

**Comment by w-shackleton** [comment]
I have just released [Network Spoofer 2.1.0](https://github.com/w-shackleton/android-netspoof/releases/tag/2.1.0) - please can you check whether this issue still happens with this new version (the app will prompt to update).

**Comment by w-shackleton** [comment]
Closing since no details given.
