### ISSUE TITLE
MagiskSU - compability

### ISSUE THREAD

**Issue by alii** [w-shackleton/android-netspoof#185]
With latest MagiskSU and MagiskSU installed (12.0 as of today), it just doesn't request root access. I don't know why!

**Comment by Systemad** [comment]
With the latest magisk version, 
open Network Spoofer go-to settings and change custom "su" location to
>/sbin/su

**Comment by thewire1o1** [comment]
this does not work for me... still get unrooted device message

**Comment by writeshh** [comment]
Yeah /sbin/su is not working. Magisk v16.00

**Comment by Systemad** [comment]
Remove "/"

sbin/su

Works for me.

**Comment by jebyjoseph** [comment]
Just download superuser pro apk and open the app again. It will work

**Comment by jebyjoseph** [comment]
/sbin/su
Click ok , then close the app and open again.
It will work

**Comment by MrRobotAptoide** [comment]
Thanks 😊 works

**Comment by YoBoiiiErik** [comment]
Hey i was just wondering about network spoofer... when i try to use one of the spoofs it says that i need android 5.0 or later when i litterally have oreo 8.0! I DONT GET IT WHY DOES IT SAY ERROR!? And yes i did the sbin/su thing and it detected the magiskSU but it still shows errors when i try to spoof. Please help. - Erik
