### ISSUE TITLE
Permission Denied Error

### ISSUE THREAD

**Issue by Jack-Rickwood** [w-shackleton/android-netspoof#213]
After setting the custom root path to /sbin/su it detects root fine, but the app still wont work! I just get this error: "Unable to retrieve local hardware address libnet ( ioctl: Permission Denied )." Is this just because the app is outdated, or my phone (sm-g930f) is not supported? Is there any way i can fix this?

**Comment by alii** [comment]
Are you fully rooted and using the latest version of Magisk?

**Comment by Jack-Rickwood** [comment]
Yep, its weird. Honestly forgot i made this issue.

**Comment by Jack-Rickwood** [comment]
@aabbccsmith holy shit i didnt get that error this time, idk why, nothing changed.

**Comment by Jack-Rickwood** [comment]
Should the output look like: "sent arp reply from [ip] to [ip]" if done correctly?
