### ISSUE TITLE
don't work help me pls

### ISSUE THREAD

**Issue by manurootas** [w-shackleton/android-netspoof#46]
Hi i have galaxy s5 (G900F) and live on italy
I have try to use your network spoofter on my phone but when i press start i recive this:
http://imgur.com/AtU8p0C
P.s: work with 3G

**Comment by Interneedus** [comment]
What's the problem?

**Comment by w-shackleton** [comment]
I've just released [Network Spoofer 2.2.0](https://github.com/w-shackleton/android-netspoof/releases/tag/2.2.0) - does this fix it?

**Comment by w-shackleton** [comment]
Merging with issue #53
