### ISSUE TITLE
HTTPS ?

### ISSUE THREAD

**Issue by Demaz93** [w-shackleton/android-netspoof#47]
I noticed that some mode like "change image", "redirect custom", ecc doesn't work on https. I tryed change image but on facebook doesn't work, I tryed replace words it works everywhere but not on facebook(https), google search(https). I don't know if https it could be the problem.

Thank you

Device: Galaxy s4 cyanogenmod 11

**Comment by w-shackleton** [comment]
The reason that lots of people use HTTPS is that it's invulnerable to attacks like those used in Network Spoofer.
