### ISSUE TITLE
sad...

### ISSUE THREAD

**Issue by 0SomeonE0** [w-shackleton/android-netspoof#48]
It's don't spoof, just closing coming int! I want something more!

**Comment by Interneedus** [comment]
Please give more information.

**Comment by w-shackleton** [comment]
I've just released [Network Spoofer 2.2.0](https://github.com/w-shackleton/android-netspoof/releases/tag/2.2.0) - does this fix it?

**Comment by w-shackleton** [comment]
Closing since no details given.
