### ISSUE TITLE
error: only position independent executables (PIE) are allowed.

### ISSUE THREAD

**Issue by sotiris84** [w-shackleton/android-netspoof#50]
Hi. I am using a Nexus 5 with the official Android 5.0.1 image (no custom rom), rooted of course and every time I try to enable any spoof I get the above error. I use the latest version of netspoof (2.1.1). I did a little search on the internet and this might be of some help to you. Thank you for taking the time to create this great tool!
http://stackoverflow.com/questions/24818902/running-a-native-library-on-android-l-error-only-position-independent-executab

**Comment by w-shackleton** [comment]
Ah excellent! I'll do what that article says.

**Comment by w-shackleton** [comment]
Here's a version that contains android-16 built executables as well as android-9 ones: https://dl.dropboxusercontent.com/u/9091715/android-netspoof/androidnetspoof-PIE-alpha.apk

I've marked this issue as closed, but that doesn't mean Network Spoofer will work on Lollipop yet :disappointed: - there will likely still be other bugs present in Lollipop that need fixing first.

**Comment by sotiris84** [comment]
Wow that was fast. The new version does not provide any errors, but it still doesn't work in Lollipop. If you need a beta tester for Lollipop, let me know! Keep up the good work!

**Comment by w-shackleton** [comment]
Thanks, I'll keep that in mind.
