### ISSUE TITLE
cSploit

### ISSUE THREAD

**Issue by Interneedus** [w-shackleton/android-netspoof#52]
Have you thought of working on cSploit instead of netspoof? 
cSploit could use some extra developers. Netspoof has some pretty neat features but it lacks a lot, these two together would be really neat. (Netspoof scripts, MITM scripts, basically all from netspoof would be great)

**Comment by w-shackleton** [comment]
I'll have a look at cSploit at some point - if I have some spare time I'll try to add some features.

**Comment by Avamander** [comment]
But merge?
