### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by luaka** [w-shackleton/android-netspoof#55]
I use net spoof and I can't back images to normal.Please help me.

**Comment by luaka** [comment]
HELP

**Comment by Interneedus** [comment]
Please give us more details.

**Comment by luaka** [comment]
I use rotate all images upside down and when I stop spoof images stays upside down

**Comment by luaka** [comment]
I have Samsung galaxy S5

**Comment by w-shackleton** [comment]
Reset your browser cache. The browser caches the flipped images and keeps serving them to you. In Chrome, press `Ctrl+Shift+Delete` then follow the dialog.
