### ISSUE TITLE
Not Working on Galaxy S Blaze (4G)

### ISSUE THREAD

**Issue by dylanpdx** [w-shackleton/android-netspoof#56]
Hey there!

I downloaded NetSpoof the other day to play a little prank on a friend (with permission), however, It didn't work on my phone. The app starts and latches onto the IP, but then the person who the hack is being used on loses all internet connection. I figured since you want the app to be compatible with most devices, I would help out and give you mine. 

I am using a Samsung Galaxy Blaze running 4.4.4 (CyanogenMod), using the latest version of NetSpoof (2.1.1)

Let me know if there's anything else that you need!

Thanks in advance

**Comment by w-shackleton** [comment]
I've just released [Network Spoofer 2.2.1](https://github.com/w-shackleton/android-netspoof/releases/tag/2.2.1) - please can you check with this version?

**Comment by dylanpdx** [comment]
@w-shackleton Thanks! That fixed the issue.
