### ISSUE TITLE
Subnet scanning never finishes

### ISSUE THREAD

**Issue by w-shackleton** [w-shackleton/android-netspoof#68]
@iKlem
> So, I have tested 3 times and i have the same result for the 1st and the 2nd : 
> 1. The application start normally
> 2. Selection of spoof 
> 3. Selection of Gateway (Default)
> 4. Accepting the Su prompt
> 5. Waiting for "Scanning for devices..." (i wait 5 min approximately)
> 6. Pushed the "Back" button to the start
> 7. Selection of another spoof
> 8. Selection of the same Gateway
> 9. And wait again...
> 
> With the first test, it crashes my phone
> The second crash after the 3rd "Back and selection spoof/selection Gateway"
> The 3rd test is made with the "Other" option and it worked.
> 
> EDIT : It's worked for the 3rd time, but it crashed my phone two minutes after quitting the app.

**Comment by iKlem** [comment]
YAY ! The 2.3.0 works for me now !
Good job and keep going on your work :D
For the Blue Ball Spoof, i had to do a ipconfig /release and ipconfig /renew after because it redirect me all the time.

**Comment by w-shackleton** [comment]
Excellent news! :smiley: 
The blue ball spoof redirects clients with a 301 permanent redirect (rather than a temporary redirect) - this makes it quite funny when browsers cache this since it's quite hard to get it to stop redirecting. I usually find that clearing the victim's browser cache works.
