### ISSUE TITLE
When Running it works as DDOS

### ISSUE THREAD

**Issue by joaolongo** [w-shackleton/android-netspoof#69]
When i try to use any feature on a computer, it makes the computer disconnect from the internet and the feature doesn't work. It only works as an DDOS app for me.

**Comment by w-shackleton** [comment]
What kind of computer are you trying to attack? What type of network are you trying to perform the attack over? Which version of Android are you running, and which version of Network Spoofer are you using?

**Comment by joaolongo** [comment]
Computer --> Windows 8.1 Hp All-In-One
Network --> Wireless network with WPA/WPA2-PSK
Android --> I had this issue on 4.4.4 Carbon Rom, 5.0.1 CM12 and 5.0.1 BlissPop
NetSpoof Version --> I always use the latest version
