### ISSUE TITLE
fake 

### ISSUE THREAD

**Issue by sinistermachine** [w-shackleton/android-netspoof#74]
Your "project" so far is working like a well crafted peice of fakery. If you disagree then let me know how to manually set everything up so I can see at least one of your supposed outcomes...cause not one is working as you claim it should.

**Comment by Avamander** [comment]
It's not fake because you don't know how to use it. Also, being rude won't help you.

**Comment by sinistermachine** [comment]
I apologize for the rudeness. I was out of line. I do regret my actions and
I recognize my misplaced frustration was unnecessarily directed at you when
it should have been directed at myself.

I would like more info that may help me achieve more promising results.

Again I do apologize and recognize your skill set as more advanced than my
own and I do require some assistance. if you would be kind enough to accept
this sincere apology, I have tested the various tests and played with
different configs but nothing happens, I was contemplating manipulating
IP/Routing settings but if you have an idea as to why my victim machine
isn't getting rerouted through my nexus7  id be eternaly grateful

**Comment by w-shackleton** [comment]
"Looks like a high school project"

I wrote Network Spoofer when I was 16. So, yes.
